/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VerbwireApiDocumentation.UpdateApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateApi', function() {
    describe('nftDeployUpdateContractPost', function() {
      it('should call nftDeployUpdateContractPost successfully', function(done) {
        //uncomment below and update the code to test nftDeployUpdateContractPost
        //instance.nftDeployUpdateContractPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nftDeployUpdateWithdrawFundsPost', function() {
      it('should call nftDeployUpdateWithdrawFundsPost successfully', function(done) {
        //uncomment below and update the code to test nftDeployUpdateWithdrawFundsPost
        //instance.nftDeployUpdateWithdrawFundsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nftUpdateAddToAllowListPost', function() {
      it('should call nftUpdateAddToAllowListPost successfully', function(done) {
        //uncomment below and update the code to test nftUpdateAddToAllowListPost
        //instance.nftUpdateAddToAllowListPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nftUpdateTransferOperatorPost', function() {
      it('should call nftUpdateTransferOperatorPost successfully', function(done) {
        //uncomment below and update the code to test nftUpdateTransferOperatorPost
        //instance.nftUpdateTransferOperatorPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
