/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient.js';
import AuthTokens from './model/AuthTokens.js';
import Body from './model/Body.js';
import Body1 from './model/Body1.js';
import Body10 from './model/Body10.js';
import Body11 from './model/Body11.js';
import Body12 from './model/Body12.js';
import Body13 from './model/Body13.js';
import Body14 from './model/Body14.js';
import Body15 from './model/Body15.js';
import Body16 from './model/Body16.js';
import Body17 from './model/Body17.js';
import Body18 from './model/Body18.js';
import Body19 from './model/Body19.js';
import Body2 from './model/Body2.js';
import Body20 from './model/Body20.js';
import Body21 from './model/Body21.js';
import Body22 from './model/Body22.js';
import Body23 from './model/Body23.js';
import Body24 from './model/Body24.js';
import Body25 from './model/Body25.js';
import Body3 from './model/Body3.js';
import Body4 from './model/Body4.js';
import Body5 from './model/Body5.js';
import Body6 from './model/Body6.js';
import Body7 from './model/Body7.js';
import Body8 from './model/Body8.js';
import Body9 from './model/Body9.js';
import CollectionData from './model/CollectionData.js';
import CollectionDataFloorSale from './model/CollectionDataFloorSale.js';
import CollectionDataRank from './model/CollectionDataRank.js';
import CollectionDataRoyalties from './model/CollectionDataRoyalties.js';
import CollectionDataVolume from './model/CollectionDataVolume.js';
import Error from './model/Error.js';
import FloorPrice from './model/FloorPrice.js';
import HistoricalStats from './model/HistoricalStats.js';
import InlineResponse200 from './model/InlineResponse200.js';
import InlineResponse2001 from './model/InlineResponse2001.js';
import InlineResponse20010 from './model/InlineResponse20010.js';
import InlineResponse20010Transfers from './model/InlineResponse20010Transfers.js';
import InlineResponse20011 from './model/InlineResponse20011.js';
import InlineResponse20011Collections from './model/InlineResponse20011Collections.js';
import InlineResponse20012 from './model/InlineResponse20012.js';
import InlineResponse20012Attributes from './model/InlineResponse20012Attributes.js';
import InlineResponse20013 from './model/InlineResponse20013.js';
import InlineResponse20013Attributes from './model/InlineResponse20013Attributes.js';
import InlineResponse20014 from './model/InlineResponse20014.js';
import InlineResponse20015 from './model/InlineResponse20015.js';
import InlineResponse2002 from './model/InlineResponse2002.js';
import InlineResponse2003 from './model/InlineResponse2003.js';
import InlineResponse2004 from './model/InlineResponse2004.js';
import InlineResponse2005 from './model/InlineResponse2005.js';
import InlineResponse2006 from './model/InlineResponse2006.js';
import InlineResponse2007 from './model/InlineResponse2007.js';
import InlineResponse2008 from './model/InlineResponse2008.js';
import InlineResponse2008Transfers from './model/InlineResponse2008Transfers.js';
import InlineResponse2009 from './model/InlineResponse2009.js';
import InlineResponse2009Transfers from './model/InlineResponse2009Transfers.js';
import InlineResponse201 from './model/InlineResponse201.js';
import InlineResponse2011 from './model/InlineResponse2011.js';
import InlineResponse2012 from './model/InlineResponse2012.js';
import InlineResponse2013 from './model/InlineResponse2013.js';
import InlineResponse2014 from './model/InlineResponse2014.js';
import InlineResponse400 from './model/InlineResponse400.js';
import InlineResponse4001 from './model/InlineResponse4001.js';
import NFTData from './model/NFTData.js';
import NFTDataInner from './model/NFTDataInner.js';
import NFTDetails from './model/NFTDetails.js';
import NftAttributes from './model/NftAttributes.js';
import NftAttributesWithTokens from './model/NftAttributesWithTokens.js';
import OneOfinlineResponse20010TransfersResultsItems from './model/OneOfinlineResponse20010TransfersResultsItems.js';
import OneOfinlineResponse20011CollectionsResultsItems from './model/OneOfinlineResponse20011CollectionsResultsItems.js';
import OneOfinlineResponse20012AttributesResultsItems from './model/OneOfinlineResponse20012AttributesResultsItems.js';
import OneOfinlineResponse20013AttributesResultsItems from './model/OneOfinlineResponse20013AttributesResultsItems.js';
import OneOfinlineResponse2005FloorPricesItems from './model/OneOfinlineResponse2005FloorPricesItems.js';
import OneOfinlineResponse2006HistoricalStatsItems from './model/OneOfinlineResponse2006HistoricalStatsItems.js';
import OneOfinlineResponse2007SalesItems from './model/OneOfinlineResponse2007SalesItems.js';
import OneOfinlineResponse2008TransfersResultsItems from './model/OneOfinlineResponse2008TransfersResultsItems.js';
import OneOfinlineResponse2009TransfersResultsItems from './model/OneOfinlineResponse2009TransfersResultsItems.js';
import OwnershipData from './model/OwnershipData.js';
import SalesEvent from './model/SalesEvent.js';
import Token from './model/Token.js';
import Transaction from './model/Transaction.js';
import TransactionInner from './model/TransactionInner.js';
import TransferEvent from './model/TransferEvent.js';
import User from './model/User.js';
import VwTransaction from './model/VwTransaction.js';
import BurnApi from './api/BurnApi.js';
import CrossChainSendApi from './api/CrossChainSendApi.js';
import DataApi from './api/DataApi.js';
import DeployApi from './api/DeployApi.js';
import MintApi from './api/MintApi.js';
import StoreApi from './api/StoreApi.js';
import UpdateApi from './api/UpdateApi.js';
import UserApi from './api/UserApi.js';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var VerbwireApiDocumentation = require('index'); // See note below*.
* var xxxSvc = new VerbwireApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new VerbwireApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue.js';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new VerbwireApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new VerbwireApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue.js';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export default{
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthTokens model constructor.
     * @property {module:model/AuthTokens}
     */
    AuthTokens,

    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body,

    /**
     * The Body1 model constructor.
     * @property {module:model/Body1}
     */
    Body1,

    /**
     * The Body10 model constructor.
     * @property {module:model/Body10}
     */
    Body10,

    /**
     * The Body11 model constructor.
     * @property {module:model/Body11}
     */
    Body11,

    /**
     * The Body12 model constructor.
     * @property {module:model/Body12}
     */
    Body12,

    /**
     * The Body13 model constructor.
     * @property {module:model/Body13}
     */
    Body13,

    /**
     * The Body14 model constructor.
     * @property {module:model/Body14}
     */
    Body14,

    /**
     * The Body15 model constructor.
     * @property {module:model/Body15}
     */
    Body15,

    /**
     * The Body16 model constructor.
     * @property {module:model/Body16}
     */
    Body16,

    /**
     * The Body17 model constructor.
     * @property {module:model/Body17}
     */
    Body17,

    /**
     * The Body18 model constructor.
     * @property {module:model/Body18}
     */
    Body18,

    /**
     * The Body19 model constructor.
     * @property {module:model/Body19}
     */
    Body19,

    /**
     * The Body2 model constructor.
     * @property {module:model/Body2}
     */
    Body2,

    /**
     * The Body20 model constructor.
     * @property {module:model/Body20}
     */
    Body20,

    /**
     * The Body21 model constructor.
     * @property {module:model/Body21}
     */
    Body21,

    /**
     * The Body22 model constructor.
     * @property {module:model/Body22}
     */
    Body22,

    /**
     * The Body23 model constructor.
     * @property {module:model/Body23}
     */
    Body23,

    /**
     * The Body24 model constructor.
     * @property {module:model/Body24}
     */
    Body24,

    /**
     * The Body25 model constructor.
     * @property {module:model/Body25}
     */
    Body25,

    /**
     * The Body3 model constructor.
     * @property {module:model/Body3}
     */
    Body3,

    /**
     * The Body4 model constructor.
     * @property {module:model/Body4}
     */
    Body4,

    /**
     * The Body5 model constructor.
     * @property {module:model/Body5}
     */
    Body5,

    /**
     * The Body6 model constructor.
     * @property {module:model/Body6}
     */
    Body6,

    /**
     * The Body7 model constructor.
     * @property {module:model/Body7}
     */
    Body7,

    /**
     * The Body8 model constructor.
     * @property {module:model/Body8}
     */
    Body8,

    /**
     * The Body9 model constructor.
     * @property {module:model/Body9}
     */
    Body9,

    /**
     * The CollectionData model constructor.
     * @property {module:model/CollectionData}
     */
    CollectionData,

    /**
     * The CollectionDataFloorSale model constructor.
     * @property {module:model/CollectionDataFloorSale}
     */
    CollectionDataFloorSale,

    /**
     * The CollectionDataRank model constructor.
     * @property {module:model/CollectionDataRank}
     */
    CollectionDataRank,

    /**
     * The CollectionDataRoyalties model constructor.
     * @property {module:model/CollectionDataRoyalties}
     */
    CollectionDataRoyalties,

    /**
     * The CollectionDataVolume model constructor.
     * @property {module:model/CollectionDataVolume}
     */
    CollectionDataVolume,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The FloorPrice model constructor.
     * @property {module:model/FloorPrice}
     */
    FloorPrice,

    /**
     * The HistoricalStats model constructor.
     * @property {module:model/HistoricalStats}
     */
    HistoricalStats,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20010Transfers model constructor.
     * @property {module:model/InlineResponse20010Transfers}
     */
    InlineResponse20010Transfers,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20011Collections model constructor.
     * @property {module:model/InlineResponse20011Collections}
     */
    InlineResponse20011Collections,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse20012Attributes model constructor.
     * @property {module:model/InlineResponse20012Attributes}
     */
    InlineResponse20012Attributes,

    /**
     * The InlineResponse20013 model constructor.
     * @property {module:model/InlineResponse20013}
     */
    InlineResponse20013,

    /**
     * The InlineResponse20013Attributes model constructor.
     * @property {module:model/InlineResponse20013Attributes}
     */
    InlineResponse20013Attributes,

    /**
     * The InlineResponse20014 model constructor.
     * @property {module:model/InlineResponse20014}
     */
    InlineResponse20014,

    /**
     * The InlineResponse20015 model constructor.
     * @property {module:model/InlineResponse20015}
     */
    InlineResponse20015,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2008Transfers model constructor.
     * @property {module:model/InlineResponse2008Transfers}
     */
    InlineResponse2008Transfers,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse2009Transfers model constructor.
     * @property {module:model/InlineResponse2009Transfers}
     */
    InlineResponse2009Transfers,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The InlineResponse2011 model constructor.
     * @property {module:model/InlineResponse2011}
     */
    InlineResponse2011,

    /**
     * The InlineResponse2012 model constructor.
     * @property {module:model/InlineResponse2012}
     */
    InlineResponse2012,

    /**
     * The InlineResponse2013 model constructor.
     * @property {module:model/InlineResponse2013}
     */
    InlineResponse2013,

    /**
     * The InlineResponse2014 model constructor.
     * @property {module:model/InlineResponse2014}
     */
    InlineResponse2014,

    /**
     * The InlineResponse400 model constructor.
     * @property {module:model/InlineResponse400}
     */
    InlineResponse400,

    /**
     * The InlineResponse4001 model constructor.
     * @property {module:model/InlineResponse4001}
     */
    InlineResponse4001,

    /**
     * The NFTData model constructor.
     * @property {module:model/NFTData}
     */
    NFTData,

    /**
     * The NFTDataInner model constructor.
     * @property {module:model/NFTDataInner}
     */
    NFTDataInner,

    /**
     * The NFTDetails model constructor.
     * @property {module:model/NFTDetails}
     */
    NFTDetails,

    /**
     * The NftAttributes model constructor.
     * @property {module:model/NftAttributes}
     */
    NftAttributes,

    /**
     * The NftAttributesWithTokens model constructor.
     * @property {module:model/NftAttributesWithTokens}
     */
    NftAttributesWithTokens,

    /**
     * The OneOfinlineResponse20010TransfersResultsItems model constructor.
     * @property {module:model/OneOfinlineResponse20010TransfersResultsItems}
     */
    OneOfinlineResponse20010TransfersResultsItems,

    /**
     * The OneOfinlineResponse20011CollectionsResultsItems model constructor.
     * @property {module:model/OneOfinlineResponse20011CollectionsResultsItems}
     */
    OneOfinlineResponse20011CollectionsResultsItems,

    /**
     * The OneOfinlineResponse20012AttributesResultsItems model constructor.
     * @property {module:model/OneOfinlineResponse20012AttributesResultsItems}
     */
    OneOfinlineResponse20012AttributesResultsItems,

    /**
     * The OneOfinlineResponse20013AttributesResultsItems model constructor.
     * @property {module:model/OneOfinlineResponse20013AttributesResultsItems}
     */
    OneOfinlineResponse20013AttributesResultsItems,

    /**
     * The OneOfinlineResponse2005FloorPricesItems model constructor.
     * @property {module:model/OneOfinlineResponse2005FloorPricesItems}
     */
    OneOfinlineResponse2005FloorPricesItems,

    /**
     * The OneOfinlineResponse2006HistoricalStatsItems model constructor.
     * @property {module:model/OneOfinlineResponse2006HistoricalStatsItems}
     */
    OneOfinlineResponse2006HistoricalStatsItems,

    /**
     * The OneOfinlineResponse2007SalesItems model constructor.
     * @property {module:model/OneOfinlineResponse2007SalesItems}
     */
    OneOfinlineResponse2007SalesItems,

    /**
     * The OneOfinlineResponse2008TransfersResultsItems model constructor.
     * @property {module:model/OneOfinlineResponse2008TransfersResultsItems}
     */
    OneOfinlineResponse2008TransfersResultsItems,

    /**
     * The OneOfinlineResponse2009TransfersResultsItems model constructor.
     * @property {module:model/OneOfinlineResponse2009TransfersResultsItems}
     */
    OneOfinlineResponse2009TransfersResultsItems,

    /**
     * The OwnershipData model constructor.
     * @property {module:model/OwnershipData}
     */
    OwnershipData,

    /**
     * The SalesEvent model constructor.
     * @property {module:model/SalesEvent}
     */
    SalesEvent,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The Transaction model constructor.
     * @property {module:model/Transaction}
     */
    Transaction,

    /**
     * The TransactionInner model constructor.
     * @property {module:model/TransactionInner}
     */
    TransactionInner,

    /**
     * The TransferEvent model constructor.
     * @property {module:model/TransferEvent}
     */
    TransferEvent,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The VwTransaction model constructor.
     * @property {module:model/VwTransaction}
     */
    VwTransaction,

    /**
    * The BurnApi service constructor.
    * @property {module:api/BurnApi}
    */
    BurnApi,

    /**
    * The CrossChainSendApi service constructor.
    * @property {module:api/CrossChainSendApi}
    */
    CrossChainSendApi,

    /**
    * The DataApi service constructor.
    * @property {module:api/DataApi}
    */
    DataApi,

    /**
    * The DeployApi service constructor.
    * @property {module:api/DeployApi}
    */
    DeployApi,

    /**
    * The MintApi service constructor.
    * @property {module:api/MintApi}
    */
    MintApi,

    /**
    * The StoreApi service constructor.
    * @property {module:api/StoreApi}
    */
    StoreApi,

    /**
    * The UpdateApi service constructor.
    * @property {module:api/UpdateApi}
    */
    UpdateApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
