/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient.js";
import InlineResponse20014 from '../model/InlineResponse20014.js';
import InlineResponse400 from '../model/InlineResponse400.js';

/**
* Burn service.
* @module api/BurnApi
* @version 1.0.0
*/
export default class BurnApi {

    /**
    * Constructs a new BurnApi. 
    * @alias module:api/BurnApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the nftDeployBurnPost operation.
     * @callback module:api/BurnApi~nftDeployBurnPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20014} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Burn NFT
     * Burn an NFT. You can burn only NFTs created from your own collection contract.
     * @param {module:api/BurnApi~nftDeployBurnPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20014}
     */
    nftDeployBurnPost(contractAddress, tokenId, chain, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'contractAddress': contractAddress,
        'tokenId': tokenId,
        'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = InlineResponse20014;

      return this.apiClient.callApi(
        '/nft/deploy/burn', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
