/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient.js";
import InlineResponse20014 from '../model/InlineResponse20014.js';
import InlineResponse400 from '../model/InlineResponse400.js';

/**
* Mint service.
* @module api/MintApi
* @version 1.0.0
*/
export default class MintApi {

    /**
    * Constructs a new MintApi. 
    * @alias module:api/MintApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the nftMintCollectionReserveMintPost operation.
     * @callback module:api/MintApi~nftMintCollectionReserveMintPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20014} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Mint to a Wallet Address
     * Mint an NFT to a provided address. Works with only collection contracts.
     * @param {module:api/MintApi~nftMintCollectionReserveMintPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20014}
     */
    nftMintCollectionReserveMintPost(mintQty, contractAddress, recipientAddress, chain, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'mintQty': mintQty,
        'contractAddress': contractAddress,
        'recipientAddress': recipientAddress,
        'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = InlineResponse20014;

      return this.apiClient.callApi(
        '/nft/mint/collectionReserveMint', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftMintCustomContractMintFromFilePost operation.
     * @callback module:api/MintApi~nftMintCustomContractMintFromFilePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20014} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Custom Contract NFT Mint from image
     * Mint an NFT from an image file using your created custom contract
     * @param {module:api/MintApi~nftMintCustomContractMintFromFilePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20014}
     */
    nftMintCustomContractMintFromFilePost(filePath, name, description, recipientAddress, contractAddress, chain, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'filePath': filePath,
        'name': name,
        'description': description,
        'recipientAddress': recipientAddress,
        'contractAddress': contractAddress,
        'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = InlineResponse20014;

      return this.apiClient.callApi(
        '/nft/mint/customContractMintFromFile', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftMintCustomContractMintFromMetadataUrlPost operation.
     * @callback module:api/MintApi~nftMintCustomContractMintFromMetadataUrlPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20014} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Mint Custom contract NFT
     * Mint an NFT from a provided metadata json file URL using your created custom contract
     * @param {module:api/MintApi~nftMintCustomContractMintFromMetadataUrlPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20014}
     */
    nftMintCustomContractMintFromMetadataUrlPost(metadataUrl, contractAddress, recipientAddress, chain, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'metadataUrl': metadataUrl,
        'contractAddress': contractAddress,
        'recipientAddress': recipientAddress,
        'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = InlineResponse20014;

      return this.apiClient.callApi(
        '/nft/mint/customContractMintFromMetadataUrl', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftMintQuickMintFromFilePost operation.
     * @callback module:api/MintApi~nftMintQuickMintFromFilePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20014} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Quick mint Omnichain NFT from image
     * Mint an Omnichain NFT directly from your specified image file in seconds
     * @param {module:api/MintApi~nftMintQuickMintFromFilePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20014}
     */
    nftMintQuickMintFromFilePost(filePath, name, description, recipientAddress, allowPlatformToOperateToken, chain, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'filePath': filePath,
        'name': name,
        'description': description,
        'recipientAddress': recipientAddress,
        'allowPlatformToOperateToken': allowPlatformToOperateToken,
        'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = InlineResponse20014;

      return this.apiClient.callApi(
        '/nft/mint/quickMintFromFile', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftMintQuickMintFromMetadataUrlPost operation.
     * @callback module:api/MintApi~nftMintQuickMintFromMetadataUrlPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20014} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Quick mint from Metadata URL
     * Mint an Omnichain NFT directly from a provided metadata file URL
     * @param {module:api/MintApi~nftMintQuickMintFromMetadataUrlPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20014}
     */
    nftMintQuickMintFromMetadataUrlPost(metadataUrl, recipientAddress, allowPlatformToOperateToken, chain, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'metadataUrl': metadataUrl,
        'recipientAddress': recipientAddress,
        'allowPlatformToOperateToken': allowPlatformToOperateToken,
        'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = InlineResponse20014;

      return this.apiClient.callApi(
        '/nft/mint/quickMintFromMetadataUrl', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
