/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import Token from './Token.js';

/**
* The AuthTokens model module.
* @module model/AuthTokens
* @version 1.0.0
*/
export default class AuthTokens {
    /**
    * Constructs a new <code>AuthTokens</code>.
    * @alias module:model/AuthTokens
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AuthTokens</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthTokens} obj Optional instance to populate.
    * @return {module:model/AuthTokens} The populated <code>AuthTokens</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthTokens();
                        
            
            if (data.hasOwnProperty('access')) {
                obj['access'] = Token.constructFromObject(data['access']);
            }
            if (data.hasOwnProperty('refresh')) {
                obj['refresh'] = Token.constructFromObject(data['refresh']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Token} access
    */
    'access' = undefined;
    /**
    * @member {module:model/Token} refresh
    */
    'refresh' = undefined;




}
