/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The Body7 model module.
* @module model/Body7
* @version 1.0.0
*/
export default class Body7 {
    /**
    * Constructs a new <code>Body7</code>.
    * @alias module:model/Body7
    * @class
    * @param metadataUrl {String} 
    * @param recipientAddress {String} 
    * @param chain {module:model/Body7.ChainEnum} 
    */

    constructor(metadataUrl, recipientAddress, chain) {
        
        
        this['metadataUrl'] = metadataUrl;
        this['recipientAddress'] = recipientAddress;
        this['chain'] = chain;
        
    }

    /**
    * Constructs a <code>Body7</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body7} obj Optional instance to populate.
    * @return {module:model/Body7} The populated <code>Body7</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body7();
                        
            
            if (data.hasOwnProperty('metadataUrl')) {
                obj['metadataUrl'] = ApiClient.convertToType(data['metadataUrl'], 'String');
            }
            if (data.hasOwnProperty('recipientAddress')) {
                obj['recipientAddress'] = ApiClient.convertToType(data['recipientAddress'], 'String');
            }
            if (data.hasOwnProperty('allowPlatformToOperateToken')) {
                obj['allowPlatformToOperateToken'] = ApiClient.convertToType(data['allowPlatformToOperateToken'], 'String');
            }
            if (data.hasOwnProperty('chain')) {
                obj['chain'] = ApiClient.convertToType(data['chain'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} metadataUrl
    */
    'metadataUrl' = undefined;
    /**
    * @member {String} recipientAddress
    */
    'recipientAddress' = undefined;
    /**
    * @member {module:model/Body7.AllowPlatformToOperateTokenEnum} allowPlatformToOperateToken
    */
    'allowPlatformToOperateToken' = undefined;
    /**
    * @member {module:model/Body7.ChainEnum} chain
    */
    'chain' = undefined;



    /**
    * Allowed values for the <code>allowPlatformToOperateToken</code> property.
    * @enum {String}
    * @readonly
    */
    static AllowPlatformToOperateTokenEnum = {
        /**
         * value: "true"
         * @const
         */
        "true": "true",
        /**
         * value: "false"
         * @const
         */
        "false": "false"    };
    /**
    * Allowed values for the <code>chain</code> property.
    * @enum {String}
    * @readonly
    */
    static ChainEnum = {
        /**
         * value: "goerli"
         * @const
         */
        "goerli": "goerli",
        /**
         * value: "bsc-testnet"
         * @const
         */
        "bsc-testnet": "bsc-testnet",
        /**
         * value: "fuji"
         * @const
         */
        "fuji": "fuji",
        /**
         * value: "mumbai"
         * @const
         */
        "mumbai": "mumbai",
        /**
         * value: "arbitrum-goerli"
         * @const
         */
        "arbitrum-goerli": "arbitrum-goerli",
        /**
         * value: "optimism-goerli"
         * @const
         */
        "optimism-goerli": "optimism-goerli",
        /**
         * value: "fantom-testnet"
         * @const
         */
        "fantom-testnet": "fantom-testnet",
        /**
         * value: "ethereum"
         * @const
         */
        "ethereum": "ethereum",
        /**
         * value: "avalanche"
         * @const
         */
        "avalanche": "avalanche",
        /**
         * value: "polygon"
         * @const
         */
        "polygon": "polygon",
        /**
         * value: "arbitrum"
         * @const
         */
        "arbitrum": "arbitrum",
        /**
         * value: "optimism"
         * @const
         */
        "optimism": "optimism",
        /**
         * value: "fantom"
         * @const
         */
        "fantom": "fantom"    };

}
