/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The Body4 model module.
* @module model/Body4
* @version 1.0.0
*/
export default class Body4 {
    /**
    * Constructs a new <code>Body4</code>.
    * @alias module:model/Body4
    * @class
    * @param contractAddress {String} 
    * @param chain {module:model/Body4.ChainEnum} 
    */

    constructor(contractAddress, chain) {
        
        
        this['contractAddress'] = contractAddress;
        this['chain'] = chain;
        
    }

    /**
    * Constructs a <code>Body4</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body4} obj Optional instance to populate.
    * @return {module:model/Body4} The populated <code>Body4</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body4();
                        
            
            if (data.hasOwnProperty('contractAddress')) {
                obj['contractAddress'] = ApiClient.convertToType(data['contractAddress'], 'String');
            }
            if (data.hasOwnProperty('chain')) {
                obj['chain'] = ApiClient.convertToType(data['chain'], 'String');
            }
            if (data.hasOwnProperty('tokenURIPrereveal')) {
                obj['tokenURIPrereveal'] = ApiClient.convertToType(data['tokenURIPrereveal'], 'String');
            }
            if (data.hasOwnProperty('allowListMintStartTime')) {
                obj['allowListMintStartTime'] = ApiClient.convertToType(data['allowListMintStartTime'], 'String');
            }
            if (data.hasOwnProperty('publicSaleStartTime')) {
                obj['publicSaleStartTime'] = ApiClient.convertToType(data['publicSaleStartTime'], 'String');
            }
            if (data.hasOwnProperty('allowlistMintPriceInWei')) {
                obj['allowlistMintPriceInWei'] = ApiClient.convertToType(data['allowlistMintPriceInWei'], 'String');
            }
            if (data.hasOwnProperty('publicPriceInWei')) {
                obj['publicPriceInWei'] = ApiClient.convertToType(data['publicPriceInWei'], 'String');
            }
            if (data.hasOwnProperty('metadataFrozen')) {
                obj['metadataFrozen'] = ApiClient.convertToType(data['metadataFrozen'], 'String');
            }
            if (data.hasOwnProperty('baseTokenURI')) {
                obj['baseTokenURI'] = ApiClient.convertToType(data['baseTokenURI'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} contractAddress
    */
    'contractAddress' = undefined;
    /**
    * @member {module:model/Body4.ChainEnum} chain
    */
    'chain' = undefined;
    /**
    * @member {String} tokenURIPrereveal
    */
    'tokenURIPrereveal' = undefined;
    /**
    * @member {String} allowListMintStartTime
    */
    'allowListMintStartTime' = undefined;
    /**
    * @member {String} publicSaleStartTime
    */
    'publicSaleStartTime' = undefined;
    /**
    * @member {String} allowlistMintPriceInWei
    */
    'allowlistMintPriceInWei' = undefined;
    /**
    * @member {String} publicPriceInWei
    */
    'publicPriceInWei' = undefined;
    /**
    * @member {String} metadataFrozen
    */
    'metadataFrozen' = undefined;
    /**
    * @member {String} baseTokenURI
    */
    'baseTokenURI' = undefined;



    /**
    * Allowed values for the <code>chain</code> property.
    * @enum {String}
    * @readonly
    */
    static ChainEnum = {
        /**
         * value: "goerli"
         * @const
         */
        "goerli": "goerli",
        /**
         * value: "bsc-testnet"
         * @const
         */
        "bsc-testnet": "bsc-testnet",
        /**
         * value: "fuji"
         * @const
         */
        "fuji": "fuji",
        /**
         * value: "mumbai"
         * @const
         */
        "mumbai": "mumbai",
        /**
         * value: "arbitrum-goerli"
         * @const
         */
        "arbitrum-goerli": "arbitrum-goerli",
        /**
         * value: "optimism-goerli"
         * @const
         */
        "optimism-goerli": "optimism-goerli",
        /**
         * value: "fantom-testnet"
         * @const
         */
        "fantom-testnet": "fantom-testnet",
        /**
         * value: "ethereum"
         * @const
         */
        "ethereum": "ethereum",
        /**
         * value: "bsc"
         * @const
         */
        "bsc": "bsc",
        /**
         * value: "avalanche"
         * @const
         */
        "avalanche": "avalanche",
        /**
         * value: "polygon"
         * @const
         */
        "polygon": "polygon",
        /**
         * value: "arbitrum"
         * @const
         */
        "arbitrum": "arbitrum",
        /**
         * value: "optimism"
         * @const
         */
        "optimism": "optimism",
        /**
         * value: "fantom"
         * @const
         */
        "fantom": "fantom"    };

}
