/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The Body1 model module.
* @module model/Body1
* @version 1.0.0
*/
export default class Body1 {
    /**
    * Constructs a new <code>Body1</code>.
    * @alias module:model/Body1
    * @class
    * @param contractName {String} 
    * @param contractSymbol {String} 
    * @param recipientAddress {String} 
    * @param chain {module:model/Body1.ChainEnum} 
    */

    constructor(contractName, contractSymbol, recipientAddress, chain) {
        
        
        this['contractName'] = contractName;
        this['contractSymbol'] = contractSymbol;
        this['recipientAddress'] = recipientAddress;
        this['chain'] = chain;
        
    }

    /**
    * Constructs a <code>Body1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body1} obj Optional instance to populate.
    * @return {module:model/Body1} The populated <code>Body1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body1();
                        
            
            if (data.hasOwnProperty('contractName')) {
                obj['contractName'] = ApiClient.convertToType(data['contractName'], 'String');
            }
            if (data.hasOwnProperty('contractSymbol')) {
                obj['contractSymbol'] = ApiClient.convertToType(data['contractSymbol'], 'String');
            }
            if (data.hasOwnProperty('recipientAddress')) {
                obj['recipientAddress'] = ApiClient.convertToType(data['recipientAddress'], 'String');
            }
            if (data.hasOwnProperty('chain')) {
                obj['chain'] = ApiClient.convertToType(data['chain'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} contractName
    */
    'contractName' = undefined;
    /**
    * @member {String} contractSymbol
    */
    'contractSymbol' = undefined;
    /**
    * @member {String} recipientAddress
    */
    'recipientAddress' = undefined;
    /**
    * @member {module:model/Body1.ChainEnum} chain
    */
    'chain' = undefined;



    /**
    * Allowed values for the <code>chain</code> property.
    * @enum {String}
    * @readonly
    */
    static ChainEnum = {
        /**
         * value: "goerli"
         * @const
         */
        "goerli": "goerli",
        /**
         * value: "bsc-testnet"
         * @const
         */
        "bsc-testnet": "bsc-testnet",
        /**
         * value: "fuji"
         * @const
         */
        "fuji": "fuji",
        /**
         * value: "mumbai"
         * @const
         */
        "mumbai": "mumbai",
        /**
         * value: "arbitrum-goerli"
         * @const
         */
        "arbitrum-goerli": "arbitrum-goerli",
        /**
         * value: "optimism-goerli"
         * @const
         */
        "optimism-goerli": "optimism-goerli",
        /**
         * value: "fantom-testnet"
         * @const
         */
        "fantom-testnet": "fantom-testnet",
        /**
         * value: "ethereum"
         * @const
         */
        "ethereum": "ethereum",
        /**
         * value: "bsc"
         * @const
         */
        "bsc": "bsc",
        /**
         * value: "avalanche"
         * @const
         */
        "avalanche": "avalanche",
        /**
         * value: "polygon"
         * @const
         */
        "polygon": "polygon",
        /**
         * value: "arbitrum"
         * @const
         */
        "arbitrum": "arbitrum",
        /**
         * value: "optimism"
         * @const
         */
        "optimism": "optimism",
        /**
         * value: "fantom"
         * @const
         */
        "fantom": "fantom"    };

}
