/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The CollectionDataRoyalties model module.
* @module model/CollectionDataRoyalties
* @version 1.0.0
*/
export default class CollectionDataRoyalties {
    /**
    * Constructs a new <code>CollectionDataRoyalties</code>.
    * @alias module:model/CollectionDataRoyalties
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CollectionDataRoyalties</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CollectionDataRoyalties} obj Optional instance to populate.
    * @return {module:model/CollectionDataRoyalties} The populated <code>CollectionDataRoyalties</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectionDataRoyalties();
                        
            
            if (data.hasOwnProperty('bps')) {
                obj['bps'] = ApiClient.convertToType(data['bps'], 'Number');
            }
            if (data.hasOwnProperty('recipient')) {
                obj['recipient'] = ApiClient.convertToType(data['recipient'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} bps
    */
    'bps' = undefined;
    /**
    * @member {String} recipient
    */
    'recipient' = undefined;




}
