/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The CollectionDataVolume model module.
* @module model/CollectionDataVolume
* @version 1.0.0
*/
export default class CollectionDataVolume {
    /**
    * Constructs a new <code>CollectionDataVolume</code>.
    * @alias module:model/CollectionDataVolume
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CollectionDataVolume</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CollectionDataVolume} obj Optional instance to populate.
    * @return {module:model/CollectionDataVolume} The populated <code>CollectionDataVolume</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectionDataVolume();
                        
            
            if (data.hasOwnProperty('1day')) {
                obj['1day'] = ApiClient.convertToType(data['1day'], 'Number');
            }
            if (data.hasOwnProperty('7day')) {
                obj['7day'] = ApiClient.convertToType(data['7day'], 'Number');
            }
            if (data.hasOwnProperty('30day')) {
                obj['30day'] = ApiClient.convertToType(data['30day'], 'Number');
            }
            if (data.hasOwnProperty('allTime')) {
                obj['allTime'] = ApiClient.convertToType(data['allTime'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} 1day
    */
    '1day' = undefined;
    /**
    * @member {Number} 7day
    */
    '7day' = undefined;
    /**
    * @member {Number} 30day
    */
    '30day' = undefined;
    /**
    * @member {Number} allTime
    */
    'allTime' = undefined;




}
