/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The HistoricalStats model module.
* @module model/HistoricalStats
* @version 1.0.0
*/
export default class HistoricalStats {
    /**
    * Constructs a new <code>HistoricalStats</code>.
    * @alias module:model/HistoricalStats
    * @class
    */

    constructor() {
        
        OneOfinlineResponse2006HistoricalStatsItems.call(this);
        
    }

    /**
    * Constructs a <code>HistoricalStats</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HistoricalStats} obj Optional instance to populate.
    * @return {module:model/HistoricalStats} The populated <code>HistoricalStats</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HistoricalStats();
                        
            
            if (data.hasOwnProperty('eventType')) {
                obj['eventType'] = ApiClient.convertToType(data['eventType'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('contractId')) {
                obj['contractId'] = ApiClient.convertToType(data['contractId'], 'String');
            }
            if (data.hasOwnProperty('chain')) {
                obj['chain'] = ApiClient.convertToType(data['chain'], 'String');
            }
            if (data.hasOwnProperty('floorSale')) {
                obj['floorSale'] = ApiClient.convertToType(data['floorSale'], 'Number');
            }
            if (data.hasOwnProperty('salesCount')) {
                obj['salesCount'] = ApiClient.convertToType(data['salesCount'], 'Number');
            }
            if (data.hasOwnProperty('rank')) {
                obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
            }
            if (data.hasOwnProperty('volume')) {
                obj['volume'] = ApiClient.convertToType(data['volume'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} eventType
    */
    'eventType' = undefined;
    /**
    * @member {String} slug
    */
    'slug' = undefined;
    /**
    * @member {String} contractId
    */
    'contractId' = undefined;
    /**
    * @member {String} chain
    */
    'chain' = undefined;
    /**
    * @member {Number} floorSale
    */
    'floorSale' = undefined;
    /**
    * @member {Number} salesCount
    */
    'salesCount' = undefined;
    /**
    * @member {Number} rank
    */
    'rank' = undefined;
    /**
    * @member {Number} volume
    */
    'volume' = undefined;
    /**
    * @member {String} timestamp
    */
    'timestamp' = undefined;

    // Implement OneOfinlineResponse2006HistoricalStatsItems interface:
    


}
