/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import Transaction from './Transaction.js';

/**
* The InlineResponse2002 model module.
* @module model/InlineResponse2002
* @version 1.0.0
*/
export default class InlineResponse2002 {
    /**
    * Constructs a new <code>InlineResponse2002</code>.
    * @alias module:model/InlineResponse2002
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>InlineResponse2002</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2002} obj Optional instance to populate.
    * @return {module:model/InlineResponse2002} The populated <code>InlineResponse2002</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2002();
                        
            
            if (data.hasOwnProperty('contract_transactions')) {
                obj['contract_transactions'] = Transaction.constructFromObject(data['contract_transactions']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Transaction} contract_transactions
    */
    'contract_transactions' = undefined;




}
