/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import VwTransaction from './VwTransaction.js';

/**
* The InlineResponse20014 model module.
* @module model/InlineResponse20014
* @version 1.0.0
*/
export default class InlineResponse20014 {
    /**
    * Constructs a new <code>InlineResponse20014</code>.
    * @alias module:model/InlineResponse20014
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>InlineResponse20014</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse20014} obj Optional instance to populate.
    * @return {module:model/InlineResponse20014} The populated <code>InlineResponse20014</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20014();
                        
            
            if (data.hasOwnProperty('transaction_details')) {
                obj['transaction_details'] = VwTransaction.constructFromObject(data['transaction_details']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/VwTransaction} transaction_details
    */
    'transaction_details' = undefined;




}
