/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The NftAttributesWithTokens model module.
* @module model/NftAttributesWithTokens
* @version 1.0.0
*/
export default class NftAttributesWithTokens {
    /**
    * Constructs a new <code>NftAttributesWithTokens</code>.
    * @alias module:model/NftAttributesWithTokens
    * @class
    */

    constructor() {
        
        OneOfinlineResponse20013AttributesResultsItems.call(this);
        
    }

    /**
    * Constructs a <code>NftAttributesWithTokens</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NftAttributesWithTokens} obj Optional instance to populate.
    * @return {module:model/NftAttributesWithTokens} The populated <code>NftAttributesWithTokens</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NftAttributesWithTokens();
                        
            
            if (data.hasOwnProperty('contractId')) {
                obj['contractId'] = ApiClient.convertToType(data['contractId'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('tokens')) {
                obj['tokens'] = ApiClient.convertToType(data['tokens'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} contractId
    */
    'contractId' = undefined;
    /**
    * @member {String} slug
    */
    'slug' = undefined;
    /**
    * @member {String} key
    */
    'key' = undefined;
    /**
    * @member {String} value
    */
    'value' = undefined;
    /**
    * @member {Number} count
    */
    'count' = undefined;
    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {Array.<String>} tokens
    */
    'tokens' = undefined;

    // Implement OneOfinlineResponse20013AttributesResultsItems interface:
    


}
