/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The NFTDetails model module.
* @module model/NFTDetails
* @version 1.0.0
*/
export default class NFTDetails {
    /**
    * Constructs a new <code>NFTDetails</code>.
    * @alias module:model/NFTDetails
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NFTDetails</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NFTDetails} obj Optional instance to populate.
    * @return {module:model/NFTDetails} The populated <code>NFTDetails</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NFTDetails();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('tokenId')) {
                obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
            }
            if (data.hasOwnProperty('tokenURI')) {
                obj['tokenURI'] = ApiClient.convertToType(data['tokenURI'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} symbol
    */
    'symbol' = undefined;
    /**
    * @member {String} tokenId
    */
    'tokenId' = undefined;
    /**
    * @member {String} owner
    */
    'owner' = undefined;
    /**
    * @member {String} tokenURI
    */
    'tokenURI' = undefined;




}
