/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The NFTDataInner model module.
* @module model/NFTDataInner
* @version 1.0.0
*/
export default class NFTDataInner {
    /**
    * Constructs a new <code>NFTDataInner</code>.
    * @alias module:model/NFTDataInner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NFTDataInner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NFTDataInner} obj Optional instance to populate.
    * @return {module:model/NFTDataInner} The populated <code>NFTDataInner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NFTDataInner();
                        
            
            if (data.hasOwnProperty('contractAddress')) {
                obj['contractAddress'] = ApiClient.convertToType(data['contractAddress'], 'String');
            }
            if (data.hasOwnProperty('tokenID')) {
                obj['tokenID'] = ApiClient.convertToType(data['tokenID'], 'String');
            }
            if (data.hasOwnProperty('tokenName')) {
                obj['tokenName'] = ApiClient.convertToType(data['tokenName'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} contractAddress
    */
    'contractAddress' = undefined;
    /**
    * @member {String} tokenID
    */
    'tokenID' = undefined;
    /**
    * @member {String} tokenName
    */
    'tokenName' = undefined;




}
