/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import NFTDataInner from './NFTDataInner.js';

/**
* The NFTData model module.
* @module model/NFTData
* @version 1.0.0
*/
export default class NFTData extends Array {
    /**
    * Constructs a new <code>NFTData</code>.
    * @alias module:model/NFTData
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>NFTData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NFTData} obj Optional instance to populate.
    * @return {module:model/NFTData} The populated <code>NFTData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NFTData();
            ApiClient.constructFromObject(data, obj, 'NFTDataInner');
            
            
        }
        return obj;
    }





}
