/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The OneOfinlineResponse20011CollectionsResultsItems model module.
* @module model/OneOfinlineResponse20011CollectionsResultsItems
* @version 1.0.0
*/
export default class OneOfinlineResponse20011CollectionsResultsItems {
    /**
    * Constructs a new <code>OneOfinlineResponse20011CollectionsResultsItems</code>.
    * @alias module:model/OneOfinlineResponse20011CollectionsResultsItems
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OneOfinlineResponse20011CollectionsResultsItems</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OneOfinlineResponse20011CollectionsResultsItems} obj Optional instance to populate.
    * @return {module:model/OneOfinlineResponse20011CollectionsResultsItems} The populated <code>OneOfinlineResponse20011CollectionsResultsItems</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneOfinlineResponse20011CollectionsResultsItems();
                        
            
        }
        return obj;
    }





}
