/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The OneOfinlineResponse2006HistoricalStatsItems model module.
* @module model/OneOfinlineResponse2006HistoricalStatsItems
* @version 1.0.0
*/
export default class OneOfinlineResponse2006HistoricalStatsItems {
    /**
    * Constructs a new <code>OneOfinlineResponse2006HistoricalStatsItems</code>.
    * @alias module:model/OneOfinlineResponse2006HistoricalStatsItems
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OneOfinlineResponse2006HistoricalStatsItems</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OneOfinlineResponse2006HistoricalStatsItems} obj Optional instance to populate.
    * @return {module:model/OneOfinlineResponse2006HistoricalStatsItems} The populated <code>OneOfinlineResponse2006HistoricalStatsItems</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneOfinlineResponse2006HistoricalStatsItems();
                        
            
        }
        return obj;
    }





}
