/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The SalesEvent model module.
* @module model/SalesEvent
* @version 1.0.0
*/
export default class SalesEvent {
    /**
    * Constructs a new <code>SalesEvent</code>.
    * @alias module:model/SalesEvent
    * @class
    */

    constructor() {
        
        OneOfinlineResponse2007SalesItems.call(this);
        
    }

    /**
    * Constructs a <code>SalesEvent</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SalesEvent} obj Optional instance to populate.
    * @return {module:model/SalesEvent} The populated <code>SalesEvent</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SalesEvent();
                        
            
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('eventType')) {
                obj['eventType'] = ApiClient.convertToType(data['eventType'], 'String');
            }
            if (data.hasOwnProperty('orderSide')) {
                obj['orderSide'] = ApiClient.convertToType(data['orderSide'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('chain')) {
                obj['chain'] = ApiClient.convertToType(data['chain'], 'String');
            }
            if (data.hasOwnProperty('sale')) {
                obj['sale'] = ApiClient.convertToType(data['sale'], 'Number');
            }
            if (data.hasOwnProperty('saleUsd')) {
                obj['saleUsd'] = ApiClient.convertToType(data['saleUsd'], 'Number');
            }
            if (data.hasOwnProperty('contractId')) {
                obj['contractId'] = ApiClient.convertToType(data['contractId'], 'String');
            }
            if (data.hasOwnProperty('tokenId')) {
                obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('block')) {
                obj['block'] = ApiClient.convertToType(data['block'], 'String');
            }
            if (data.hasOwnProperty('txHash')) {
                obj['txHash'] = ApiClient.convertToType(data['txHash'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} source
    */
    'source' = undefined;
    /**
    * @member {String} eventType
    */
    'eventType' = undefined;
    /**
    * @member {String} orderSide
    */
    'orderSide' = undefined;
    /**
    * @member {String} slug
    */
    'slug' = undefined;
    /**
    * @member {String} chain
    */
    'chain' = undefined;
    /**
    * @member {Number} sale
    */
    'sale' = undefined;
    /**
    * @member {Number} saleUsd
    */
    'saleUsd' = undefined;
    /**
    * @member {String} contractId
    */
    'contractId' = undefined;
    /**
    * @member {String} tokenId
    */
    'tokenId' = undefined;
    /**
    * @member {String} from
    */
    'from' = undefined;
    /**
    * @member {String} to
    */
    'to' = undefined;
    /**
    * @member {String} block
    */
    'block' = undefined;
    /**
    * @member {String} txHash
    */
    'txHash' = undefined;
    /**
    * @member {String} timestamp
    */
    'timestamp' = undefined;

    // Implement OneOfinlineResponse2007SalesItems interface:
    


}
