/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The TransactionInner model module.
* @module model/TransactionInner
* @version 1.0.0
*/
export default class TransactionInner {
    /**
    * Constructs a new <code>TransactionInner</code>.
    * @alias module:model/TransactionInner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TransactionInner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TransactionInner} obj Optional instance to populate.
    * @return {module:model/TransactionInner} The populated <code>TransactionInner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionInner();
                        
            
            if (data.hasOwnProperty('blockNumber')) {
                obj['blockNumber'] = ApiClient.convertToType(data['blockNumber'], 'String');
            }
            if (data.hasOwnProperty('timeStamp')) {
                obj['timeStamp'] = ApiClient.convertToType(data['timeStamp'], 'String');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('nonce')) {
                obj['nonce'] = ApiClient.convertToType(data['nonce'], 'String');
            }
            if (data.hasOwnProperty('blockHash')) {
                obj['blockHash'] = ApiClient.convertToType(data['blockHash'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('contractAddress')) {
                obj['contractAddress'] = ApiClient.convertToType(data['contractAddress'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('tokenID')) {
                obj['tokenID'] = ApiClient.convertToType(data['tokenID'], 'String');
            }
            if (data.hasOwnProperty('tokenName')) {
                obj['tokenName'] = ApiClient.convertToType(data['tokenName'], 'String');
            }
            if (data.hasOwnProperty('tokenSymbol')) {
                obj['tokenSymbol'] = ApiClient.convertToType(data['tokenSymbol'], 'String');
            }
            if (data.hasOwnProperty('tokenDecimal')) {
                obj['tokenDecimal'] = ApiClient.convertToType(data['tokenDecimal'], 'String');
            }
            if (data.hasOwnProperty('transactionIndex')) {
                obj['transactionIndex'] = ApiClient.convertToType(data['transactionIndex'], 'String');
            }
            if (data.hasOwnProperty('gas')) {
                obj['gas'] = ApiClient.convertToType(data['gas'], 'String');
            }
            if (data.hasOwnProperty('gasPrice')) {
                obj['gasPrice'] = ApiClient.convertToType(data['gasPrice'], 'String');
            }
            if (data.hasOwnProperty('gasUsed')) {
                obj['gasUsed'] = ApiClient.convertToType(data['gasUsed'], 'String');
            }
            if (data.hasOwnProperty('cumulativeGasUsed')) {
                obj['cumulativeGasUsed'] = ApiClient.convertToType(data['cumulativeGasUsed'], 'String');
            }
            if (data.hasOwnProperty('input')) {
                obj['input'] = ApiClient.convertToType(data['input'], 'String');
            }
            if (data.hasOwnProperty('confirmations')) {
                obj['confirmations'] = ApiClient.convertToType(data['confirmations'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} blockNumber
    */
    'blockNumber' = undefined;
    /**
    * @member {String} timeStamp
    */
    'timeStamp' = undefined;
    /**
    * @member {String} hash
    */
    'hash' = undefined;
    /**
    * @member {String} nonce
    */
    'nonce' = undefined;
    /**
    * @member {String} blockHash
    */
    'blockHash' = undefined;
    /**
    * @member {String} from
    */
    'from' = undefined;
    /**
    * @member {String} contractAddress
    */
    'contractAddress' = undefined;
    /**
    * @member {String} to
    */
    'to' = undefined;
    /**
    * @member {String} tokenID
    */
    'tokenID' = undefined;
    /**
    * @member {String} tokenName
    */
    'tokenName' = undefined;
    /**
    * @member {String} tokenSymbol
    */
    'tokenSymbol' = undefined;
    /**
    * @member {String} tokenDecimal
    */
    'tokenDecimal' = undefined;
    /**
    * @member {String} transactionIndex
    */
    'transactionIndex' = undefined;
    /**
    * @member {String} gas
    */
    'gas' = undefined;
    /**
    * @member {String} gasPrice
    */
    'gasPrice' = undefined;
    /**
    * @member {String} gasUsed
    */
    'gasUsed' = undefined;
    /**
    * @member {String} cumulativeGasUsed
    */
    'cumulativeGasUsed' = undefined;
    /**
    * @member {String} input
    */
    'input' = undefined;
    /**
    * @member {String} confirmations
    */
    'confirmations' = undefined;




}
