/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
* The VwTransaction model module.
* @module model/VwTransaction
* @version 1.0.0
*/
export default class VwTransaction {
    /**
    * Constructs a new <code>VwTransaction</code>.
    * @alias module:model/VwTransaction
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>VwTransaction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VwTransaction} obj Optional instance to populate.
    * @return {module:model/VwTransaction} The populated <code>VwTransaction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VwTransaction();
                        
            
            if (data.hasOwnProperty('transactionID')) {
                obj['transactionID'] = ApiClient.convertToType(data['transactionID'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} transactionID
    */
    'transactionID' = undefined;
    /**
    * @member {String} status
    */
    'status' = undefined;




}
