/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VerbwireApiDocumentation.CollectionData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CollectionData', function() {
    it('should create an instance of CollectionData', function() {
      // uncomment below and update the code to test CollectionData
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be.a(VerbwireApiDocumentation.CollectionData);
    });

    it('should have the property chain (base name: "chain")', function() {
      // uncomment below and update the code to test the property chain
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property discordUrl (base name: "discordUrl")', function() {
      // uncomment below and update the code to test the property discordUrl
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property externalUrl (base name: "externalUrl")', function() {
      // uncomment below and update the code to test the property externalUrl
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property floorSale (base name: "floorSale")', function() {
      // uncomment below and update the code to test the property floorSale
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property image (base name: "image")', function() {
      // uncomment below and update the code to test the property image
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property onSaleCount (base name: "onSaleCount")', function() {
      // uncomment below and update the code to test the property onSaleCount
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property primaryContract (base name: "primaryContract")', function() {
      // uncomment below and update the code to test the property primaryContract
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property rank (base name: "rank")', function() {
      // uncomment below and update the code to test the property rank
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property royalties (base name: "royalties")', function() {
      // uncomment below and update the code to test the property royalties
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property tokenCount (base name: "tokenCount")', function() {
      // uncomment below and update the code to test the property tokenCount
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property twitterUsername (base name: "twitterUsername")', function() {
      // uncomment below and update the code to test the property twitterUsername
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property volume (base name: "volume")', function() {
      // uncomment below and update the code to test the property volume
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new VerbwireApiDocumentation.CollectionData();
      //expect(instance).to.be();
    });

  });

}));
