/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VerbwireApiDocumentation.FloorPrice();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FloorPrice', function() {
    it('should create an instance of FloorPrice', function() {
      // uncomment below and update the code to test FloorPrice
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be.a(VerbwireApiDocumentation.FloorPrice);
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be();
    });

    it('should have the property eventType (base name: "eventType")', function() {
      // uncomment below and update the code to test the property eventType
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be();
    });

    it('should have the property kind (base name: "kind")', function() {
      // uncomment below and update the code to test the property kind
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be();
    });

    it('should have the property chain (base name: "chain")', function() {
      // uncomment below and update the code to test the property chain
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be();
    });

    it('should have the property floorAsk (base name: "floorAsk")', function() {
      // uncomment below and update the code to test the property floorAsk
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be();
    });

    it('should have the property previousFloorAsk (base name: "previousFloorAsk")', function() {
      // uncomment below and update the code to test the property previousFloorAsk
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be();
    });

    it('should have the property contractId (base name: "contractId")', function() {
      // uncomment below and update the code to test the property contractId
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new VerbwireApiDocumentation.FloorPrice();
      //expect(instance).to.be();
    });

  });

}));
