/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VerbwireApiDocumentation.OwnershipData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OwnershipData', function() {
    it('should create an instance of OwnershipData', function() {
      // uncomment below and update the code to test OwnershipData
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be.a(VerbwireApiDocumentation.OwnershipData);
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property chain (base name: "chain")', function() {
      // uncomment below and update the code to test the property chain
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property contractId (base name: "contractId")', function() {
      // uncomment below and update the code to test the property contractId
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property tokenCount (base name: "tokenCount")', function() {
      // uncomment below and update the code to test the property tokenCount
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property floorAskPrice (base name: "floorAskPrice")', function() {
      // uncomment below and update the code to test the property floorAskPrice
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property onSaleCount (base name: "onSaleCount")', function() {
      // uncomment below and update the code to test the property onSaleCount
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property topBidValue (base name: "topBidValue")', function() {
      // uncomment below and update the code to test the property topBidValue
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property totalBidValue (base name: "totalBidValue")', function() {
      // uncomment below and update the code to test the property totalBidValue
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "lastUpdated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instane = new VerbwireApiDocumentation.OwnershipData();
      //expect(instance).to.be();
    });

  });

}));
